# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
            ],
            managers=[
                ('posts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Forum_Post')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor_Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('response_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Forum_Post')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('correct_ans_text', models.CharField(max_length=255)),
                ('correct_ans_num', models.FloatField()),
                ('ans_text', models.CharField(max_length=255)),
                ('ans_num', models.FloatField()),
                ('ans_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='forum_post',
            name='linked_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.Question'),
        ),
    ]
