# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAssignment',
            fields=[
                ('instuctor_assignment_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorQuestion',
            fields=[
                ('instructor_question_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('correct_ans_text', models.CharField(max_length=255)),
                ('correct_ans_num', models.FloatField()),
                ('ans_type', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('student_assignment_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('parent_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.InstructorAssignment')),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('student_question_id', models.PositiveIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('ans_text', models.CharField(max_length=255)),
                ('ans_num', models.FloatField()),
                ('score', models.PositiveSmallIntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.StudentAssignment')),
                ('parent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.InstructorQuestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='forum_post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='forum_response',
            name='id',
        ),
        migrations.RemoveField(
            model_name='instructor_response',
            name='id',
        ),
        migrations.AddField(
            model_name='forum_post',
            name='forum_post_id',
            field=models.PositiveIntegerField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forum_response',
            name='forum_response_id',
            field=models.PositiveIntegerField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor_response',
            name='instructor_response_id',
            field=models.PositiveIntegerField(db_index=True, default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum_post',
            name='linked_q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.InstructorQuestion'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
