# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20171001_0917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum_Post',
            new_name='ForumPost',
        ),
        migrations.RenameModel(
            old_name='Forum_Response',
            new_name='ForumResponse',
        ),
        migrations.RenameModel(
            old_name='Instructor_Response',
            new_name='InstructorResponse',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='linked_q',
            new_name='linked_question',
        ),
    ]
